name: website
description: A website to news and podcast about Flutter
version: 0.1.2+3
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^1.0.0-beta.6
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  flutter_alien: ^0.1.1
  get_it: ^5.0.4
  google_fonts: ^1.1.1
  graphx: ^0.9.3
  injectable: ^1.0.7
  intl: ^0.16.1
  sizer: ^1.1.8
  spotify: ^0.4.0

dependency_overrides:
  xml: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^1.0.0-beta.6
  build_runner: ^1.10.11
  effective_dart: ^1.3.0
  injectable_generator: ^1.0.7
  mockito: ^4.1.3

flutter:
  uses-material-design: true
