name: website
description: A website to news and podcast about Flutter
version: 0.1.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  flutter_alien: ^0.1.1
  google_fonts: ^1.1.1
  graphx: ^0.9.3
  intl: ^0.16.1
  sizer: ^1.1.8
  spotify: ^0.4.0

dependency_overrides:
  xml: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
  mockito: ^4.1.3

flutter: null
